name: 'signin'

on:
  schedule:
    - cron: '30 16 * * *'

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Execute
        env:
          COOKIE: ${{ secrets.COOKIE }}
        run: |
          go run ./cmd/weibo-checkin
